### ISSUE TITLE
How to "import ffmpeg" error (module not found)

### ISSUE THREAD

**Issue by ghost** [hrkrx/Text2WiktionarySpeech#1]
Hi ! Thanks for your great work. I tried to run the Python script on Manjaro Linux but obtained the following error:

``$ python main.py [-i list.txt] [-o output.txt] [-l de]
Traceback (most recent call last):
  File "/home/m/Desktop/wik/main.py", line 1, in <module>
    **import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'**

I am not a technical user and could not find a way to solve the problem. All the dependencies are satisfied in my system, but I assume the issue is that :      **ffmpeg must be present in PATH**

Could you please briefly explain how to solve that issue ? or provide a link to an explanation ?

-------------------
_Sorry for such a "newbie" question, but I failed many times. I am trying to download all the audios from German Wiktionary to create a Pronunciation Dictionary for GoldenDict and distribute it freely._

**Comment by hrkrx** [comment]
The ffmpeg import is part of the package "ffmpeg-generator" if you really have satisfied all dependencies and ffmpeg is not present in your searchpath another error would be present.

As newer versions of python already include `urllib` try installing the dependencies like this: ` pip3 install beautifulsoup4 ffmpeg-generator  numpy`

ffmpeg must be present on `PATH` means, that your default search paths for binaries includes a path to your ffmpeg binaries. On linux that is usually already the case when you install ffmpeg the first time.

if you still have issues, feel free to ask further questions, even if you deem them *newbie* questions

**Comment by ghost** [comment]
Problem solved after installing the dependencies as you said : `pip3 install beautifulsoup4 ffmpeg-generator numpy`

**Thank you very much !**
